### ISSUE TITLE
Question: Is it possible to have rsync create the remote directories if they don't exist?

### ISSUE THREAD

**Issue by julie-sullivan** [Pendect/action-rsyncer#5]
First, thanks for this great action, it works great!

I was wondering if it is possible somehow to create the remote directories if they aren't there?

e.g. I am copying my local `build` directory to remote directory `/data/foo/bar/20200115` but `foo`, `bar` and `20200115` may or may not exist. 

I tried the `-R` flag for rsync and tried `mkdir --parents /tmp/foo/bar/20200115` as a flag for ssh (the latter works for me locally).

**Comment by ericof** [comment]
Hello @julie-sullivan 

A possible solution, if the **-R** flag is not working, would be to add the **--rsync-path** option to this action.

I came up with this idea reading this [question](https://stackoverflow.com/questions/9242135/how-to-force-rsync-to-create-destination-folder/19173623)

What do you think?

**Comment by ericof** [comment]
I will add to the README, but you can pass `--rsync-path="mkdir -p /data/foo/bar/20200115 && rsync"` as a flag.

Example:
```
- name: Deploy to server
  id: deploy
  uses: Pendect/action-rsyncer@v1.1.0
  env:
    DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
  with:
    flags: '-avzr --delete --rsync-path="mkdir -p /data/foo/bar/20200115 && rsync"'
    options: ''
    ssh_options: ''
    src: 'public/'
    dest: 'user@server.com:/data/foo/bar/20200115'

- name: Display status from deploy
  run: echo "${{ steps.deploy.outputs.status }}"
```
