### ISSUE TITLE
This thing sends an empty folder!

### ISSUE THREAD

**Issue by Wohlstand** [Pendect/action-rsyncer#6]
### Describe the bug 🔍

I try to make the action that uploads an entire content of repository (with excluding of hidden files), however, this thing NEVER finds me files in `/github/workspace` where it should be a repo!

### To Reproduce 💥

```
name: Auto-Upload

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        id: deploy
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with: 
          flags: '-avzr --delete --exclude=".*"'
# attempted WORKAROUND, primarly I used just "*" to upload everything
          options: '../workspace'
          ssh_options: '-q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
          src: '.'
          dest: '${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.EDITOR_HELP_REMOTE }}'
```
### Expected behavior ✨

Full content of the repo got sent to repo

### Screenshots 📸

A blank folder:
![Снимок экрана_2020-02-19_23-04-37](https://user-images.githubusercontent.com/6751442/74871251-3b055500-536c-11ea-8c36-99a56847bf09.png)
